FROM alpine:3.15

RUN apk add --update --no-cache curl

RUN addgroup curl && adduser -S -G curl curl

USER curl
WORKDIR /config
RUN touch whitelist.txt

ENV DELAY_IN_SECONDS=40
ENV WHITELIST_RAW_LINK=https://friendpaste.com/ID/raw

ENTRYPOINT while true; do curl --fail $WHITELIST_RAW_LINK -o whitelist.txt; sleep $DELAY_IN_SECONDS; done