FROM python:3.9.10-slim-buster

COPY requirements.txt .

EXPOSE 46547

RUN adduser sanic -system -group

RUN mkdir sanic
WORKDIR /sanic

RUN mkdir db
RUN chown sanic:sanic db

USER sanic

RUN pip3 install -r requirements.txt \
&& rm requirements.txt

COPY server.py .

ENV DELAY=250

ENTRYPOINT python3 server.py $DELAY
