FROM python:3.9.10-slim-buster

EXPOSE 46547

RUN adduser sanic -system -group

RUN mkdir sanic
WORKDIR /sanic

RUN mkdir db
RUN chown sanic:sanic db

USER sanic

COPY requirements.txt .

RUN pip3 install -r requirements.txt

USER root
RUN rm requirements.txt
USER sanic

COPY server.py .

ENV DELAY=250

ENTRYPOINT python3 server.py $DELAY
