FROM alpine:3.15

RUN apk add --update --no-cache curl

#RUN addgroup curl && adduser -S -G curl curl

RUN mkdir /config
#RUN chown curl:curl /config

WORKDIR /config

#USER curl
RUN touch whitelist.txt

ENV DELAY_IN_SECONDS=300
ENV WHITELIST_RAW_LINK=https://friendpaste.com/ID/raw

ENTRYPOINT while true; do curl --fail $WHITELIST_RAW_LINK -o discord.json; sleep $DELAY_IN_SECONDS; done
